### ISSUE TITLE
Plaintext input initial_value erroneously truncated to 150 characters

### ISSUE THREAD

**Issue by sgtdck** [IBM/slack-wrench#105]
**Describe the bug**
When populating a `PlainTextInput` with an initial value > 150 characters, it gets truncated at 148 characters with an added ellipsis.

**To Reproduce**

1. Create a `PlainTextInput('TBD', veryLongInitialValueExceeding150chars);
2. Render it

**Expected behavior**
the full string

**Screenshots**

**Desktop (please complete the following information):**

- OS: [e.g. iOS] MacOS Catalina
- Browser [e.g. chrome, safari] Chrome
- Version [e.g. 22] Version 90.0.4430.93 (Official Build) (x86_64)
- Slack native app: Version 4.14.1

**Additional context**

I had a browse through the code, and it appears this has been done as part of Slack Wrench, based on testing:

packages/blocks/elements.ts L314-315:
```
      // note, initial_value not documented, but max 150 based on testing
      initial_value: [150, ellipsis],
```

I asked Slack about this, and this is their reply:

> Thanks for your patience Dick.
> 
> The Block Kit team have confirmed there **isn't hard limit for the initial_value of a Plain-text input element**. In saying that, not all the characters will be visible to the user in the text box. In my test the visible limit in the text box a user can see is 77 characters (please see screenshot attached).
> 
> I do see a limit of 150 for the placeholder property of a Plain-text input element. Perhaps that's what the developer was referring to in their comment on the repo?
> 
> I hope this helps, please let me know if you have any other questions.
> 
> Mark | Platform Support Agent

I'm creating a PR for this bug, hang on :)

**Comment by barlock** [comment]
Thanks for the report. Interesting, there at least _used_ to be a limit on these fields.

The intent behind these truncations was that we were generating long text from other sources and the message would fail to send. Truncating at known limits seemed safer for the community than causing unexpected app behavior. 

Looks like we need to re-test where these limits are. 

Normally `plain_text` fields are part of a larger section or block. Which one were you working with? Could you provide a complete block that breaks? (JSON or `blocks` would be fine)

**Comment by sgtdck** [comment]
> Interesting, there at least used to be a limit on these fields.

Yep, I can imagine Slack accidentally putting the 150 char limit on both placeholder and initial_value.

> The intent behind these truncations was that we were generating long text from other sources and the message would fail to send. Truncating at known limits seemed safer for the community than causing unexpected app behavior.
> 
> Looks like we need to re-test where these limits are.

Thank you for providing context, and that sounds like a sensible approach from your point of view.
From what I understand from Slack, there is no limit on the initial value. Looking at the Block Kit Builder, it doesn't seem to barf when putting in 5000 bytes [as I did here](https://app.slack.com/block-kit-builder/TH0RA7683#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22,%22initial_value%22:%22Lorem%20ipsum%20dolor%20sit%20amet,%20consectetur%20adipiscing%20elit.%20Mauris%20vitae%20justo%20at%20lectus%20tincidunt%20facilisis%20ut%20nec%20magna.%20Nullam%20lacinia%20porttitor%20dictum.%20Nunc%20consectetur%20hendrerit%20orci%20eu%20mollis.%20Etiam%20neque%20mi,%20ullamcorper%20eu%20lacus%20sed,%20blandit%20dignissim%20enim.%20Morbi%20condimentum%20enim%20eget%20lorem%20blandit%20imperdiet.%20Mauris%20at%20luctus%20felis,%20eu%20scelerisque%20lectus.%20Praesent%20faucibus%20felis%20quam,%20quis%20interdum%20magna%20posuere%20sed.%20In%20faucibus,%20quam%20et%20tristique%20fringilla,%20arcu%20nisi%20tincidunt%20odio,%20non%20elementum%20metus%20mi%20porta%20lectus.%20Donec%20iaculis%20purus%20in%20nisi%20facilisis,%20vel%20fringilla%20nisl%20ornare.%20Nullam%20mollis%20ultricies%20nibh%20ac%20feugiat.%20Donec%20viverra%20eget%20nisl%20eget%20ultrices.%20Morbi%20rhoncus,%20nulla%20et%20aliquam%20molestie,%20libero%20orci%20bibendum%20ante,%20consectetur%20molestie%20ligula%20mauris%20sollicitudin%20nulla.%20Proin%20et%20sem%20lobortis,%20vulputate%20orci%20eu,%20porttitor%20massa.%20Aliquam%20sagittis%20lectus%20sapien,%20in%20aliquet%20sapien%20semper%20in.%20Vivamus%20dui%20ante,%20euismod%20in%20tellus%20ut,%20rhoncus%20tristique%20diam.%20Donec%20sapien%20neque,%20lobortis%20eget%20commodo%20eget,%20tincidunt%20eget%20nunc.%20In%20hac%20habitasse%20platea%20dictumst.%20Cras%20sit%20amet%20volutpat%20odio.%20Praesent%20ut%20pellentesque%20diam,%20non%20commodo%20velit.%20Duis%20cursus%20sit%20amet%20odio%20viverra%20blandit.%20Vivamus%20efficitur%20sem%20id%20aliquam%20gravida.%20Interdum%20et%20malesuada%20fames%20ac%20ante%20ipsum%20primis%20in%20faucibus.%20In%20at%20aliquam%20elit,%20sed%20dapibus%20leo.%20Sed%20consectetur%20mattis%20leo%20maximus%20mattis.%20Cras%20a%20faucibus%20arcu.%20Proin%20convallis%20tristique%20dapibus.%20Duis%20vel%20scelerisque%20nulla.%20Sed%20feugiat%20lacinia%20condimentum.%20Ut%20ac%20egestas%20quam.%20Donec%20eget%20nisl%20suscipit%20magna%20pharetra%20tincidunt%20ac%20ut%20sapien.%20Curabitur%20nec%20purus%20at%20mi%20aliquam%20lacinia.%20Pellentesque%20sit%20amet%20nisi%20id%20tellus%20condimentum%20maximus%20vel%20eu%20dui.%20Mauris%20facilisis%20consectetur%20fringilla.%20Ut%20vulputate%20nisl%20nibh,%20id%20pretium%20eros%20sagittis%20et.%20Pellentesque%20nec%20quam%20vulputate,%20ornare%20ligula%20venenatis,%20tempor%20tortor.%20Phasellus%20condimentum%20sapien%20erat,%20sit%20amet%20pretium%20massa%20commodo%20a.%20Donec%20consectetur,%20risus%20eget%20aliquam%20luctus,%20ligula%20nisl%20ultrices%20neque,%20nec%20ornare%20lacus%20libero%20sed%20turpis.%20Nam%20suscipit%20ligula%20tristique%20mi%20condimentum,%20non%20pretium%20ipsum%20eleifend.%20Vivamus%20viverra%20arcu%20velit,%20vitae%20molestie%20turpis%20condimentum%20sit%20amet.%20Sed%20sagittis%20turpis%20eu%20tellus%20rutrum,%20at%20pharetra%20arcu%20egestas.%20Donec%20semper%20ligula%20ut%20tempus%20viverra.%20Ut%20cursus%20sodales%20urna,%20eget%20volutpat%20mi%20porta%20non.%20Quisque%20commodo%20mattis%20dolor%20vel%20feugiat.%20Vivamus%20at%20ipsum%20malesuada%20sem%20luctus%20imperdiet%20non%20at%20dolor.%20Sed%20id%20mollis%20est.%20Donec%20non%20sagittis%20ipsum.%20Aliquam%20erat%20volutpat.%20Nulla%20mauris%20nunc,%20interdum%20dapibus%20tortor%20et,%20pellentesque%20accumsan%20massa.%20Aenean%20tempus%20ultrices%20ipsum%20quis%20finibus.%20Integer%20placerat%20ipsum%20non%20odio%20vulputate,%20eu%20congue%20massa%20facilisis.%20Sed%20vulputate%20aliquet%20nulla%20ut%20pharetra.%20Integer%20egestas%20enim%20ut%20arcu%20auctor,%20eget%20consequat%20magna%20feugiat.%20Mauris%20viverra%20mi%20quis%20magna%20lobortis,%20sed%20consectetur%20sapien%20blandit.%20Aenean%20cursus%20lectus%20id%20metus%20fermentum%20fermentum.%20Mauris%20sed%20tincidunt%20neque.%20Mauris%20tempus%20iaculis%20neque%20sit%20amet%20vulputate.%20Curabitur%20a%20aliquet%20mauris.%20Pellentesque%20in%20elit%20at%20orci%20accumsan%20dapibus%20at%20quis%20lacus.%20Suspendisse%20vehicula%20a%20ipsum%20aliquam%20rhoncus.%20Fusce%20urna%20orci,%20scelerisque%20sed%20scelerisque%20eget,%20tincidunt%20quis%20tortor.%20Pellentesque%20commodo%20tempus%20porta.%20Morbi%20a%20lacus%20velit.%20Suspendisse%20porta%20congue%20bibendum.%20Proin%20aliquet%20quis%20lorem%20molestie%20lacinia.%20Suspendisse%20in%20iaculis%20tortor.%20In%20hac%20habitasse%20platea%20dictumst.%20Quisque%20sodales%20nisi%20nulla,%20eget%20viverra%20urna%20tempor%20eget.%20Phasellus%20sit%20amet%20lobortis%20tellus.%20Phasellus%20metus%20mi,%20efficitur%20quis%20consectetur%20ac,%20egestas%20vel%20leo.%20In%20interdum%20risus%20eu%20fringilla%20blandit.%20Suspendisse%20aliquam,%20eros%20ac%20tincidunt%20cursus,%20sem%20sem%20commodo%20justo,%20posuere%20bibendum%20nulla%20nunc%20a%20nibh.%20Sed%20pellentesque%20tellus%20id%20elit%20sollicitudin%20sollicitudin%20in%20a%20dolor.%20Nam%20interdum%20turpis%20sit%20amet%20augue%20ullamcorper,%20eget%20viverra%20urna%20fringilla.%20In%20euismod%20urna%20at%20purus%20laoreet%20lobortis.%20Sed%20eros%20diam,%20lobortis%20eget%20pretium%20vitae,%20dignissim%20ornare%20urna.%20Maecenas%20sit%20amet%20diam%20lacinia,%20feugiat%20elit%20ac,%20sodales%20neque.%20Nulla%20a%20augue%20vitae%20ligula%20vestibulum%20porttitor.%20Suspendisse%20cursus%20varius%20massa,%20sed%20malesuada%20metus%20ultrices%20nec.%20Suspendisse%20vel%20ex%20at%20diam%20fringilla%20cursus%20at%20vitae%20felis.%20Curabitur%20ac%20interdum%20massa.%20Fusce%20ornare%20eleifend%20pharetra.%20Nulla%20iaculis%20auctor%20mauris,%20et%20dapibus%20arcu%20iaculis%20posuere.%20Aliquam%20erat%20volutpat.%20Donec%20imperdiet,%20lectus%20quis%20aliquam%20eleifend,%20tortor%20mi%20pellentesque%20augue,%20id%20auctor%20dolor%20est%20eget%20tortor.%20Cras%20tempus%20luctus%20augue,%20sed%20rutrum%20lectus%20hendrerit%20nec.%20Aliquam%20a%20nunc%20non%20sapien%20facilisis%20tincidunt%20a%20quis%20urna.%20Praesent%20mi%20lacus,%20sollicitudin%20ac%20mattis%20ac,%20venenatis%20quis%20risus.%20Quisque%20tempor%20turpis%20ut%20elit%20varius%20elementum.%20Morbi%20sed%20arcu%20suscipit,%20semper%20lorem%20at,%20laoreet%20diam.%20Quisque%20faucibus%20felis%20ac%20libero%20euismod%20rhoncus.%20Duis%20ut%20dui%20quis%20sapien%20suscipit%20tincidunt.%20Nulla%20facilisi.%20Morbi%20vulputate,%20velit%20at%20finibus%20pharetra,%20augue%20erat%20aliquet%20purus,%20vel%20interdum%20velit%20lacus%20nec%20nibh.%20Aliquam%20orci.%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%22,%22emoji%22:true%7D%7D%5D%7D)

Slack reportedly [cuts off messages at 40,000 characters](https://api.slack.com/changelog/2018-04-truncating-really-long-messages#:~:text=is%20this%20happening%3F-,What's%20changing,messages%20with%20tremendously%20long%20text). Playin around with the Block Kit Builder seems to cut off the last character only? It would need some testing indeed.

> Normally plain_text fields are part of a larger section or block. Which one were you working with? Could you provide a complete block that breaks? (JSON or blocks would be fine)

Here's my use-case with Slack Wrench:

```ts
  const initialValue = `abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr150123456789`;
  console.log(PlainTextInput('comment', initialValue, '', { multiline: true }));
```

yields:

```
{
  type: 'plain_text_input',
  action_id: 'comment',
  initial_value: 'abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr …',
  placeholder: undefined,
  multiline: true
}
```

Compare that to [the output from the Block Kit Builder](https://app.slack.com/block-kit-builder/TH0RA7683#%7B%22title%22:%7B%22type%22:%22plain_text%22,%22text%22:%22My%20App%22,%22emoji%22:true%7D,%22submit%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Submit%22,%22emoji%22:true%7D,%22type%22:%22modal%22,%22close%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Cancel%22,%22emoji%22:true%7D,%22blocks%22:%5B%7B%22type%22:%22divider%22%7D,%7B%22type%22:%22input%22,%22element%22:%7B%22type%22:%22plain_text_input%22,%22action_id%22:%22plain_text_input-action%22,%22initial_value%22:%22abcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqr150123456789%22%7D,%22label%22:%7B%22type%22:%22plain_text%22,%22text%22:%22Label%22,%22emoji%22:true%7D%7D%5D%7D)

which returns the full string without issues.

Thanks @tteltrab for checking out the Block Kit Builder in this comment https://github.com/IBM/slack-wrench/pull/106#issuecomment-831341249

**Comment by sgtdck** [comment]
NB for anyone running into this issue, the workaround is to add a `limiterOverrides` param:

```ts
import { identity } from '@slack-wrench/blocks/lib/limitHelpers';

const limiterOverrides = { initial_value: identity };
PlainTextInput('comment', initialValue, '', { multiline: true }, limiterOverrides);
```
