### ISSUE TITLE
Generate bolt app from slack app settings

### ISSUE THREAD

**Issue by jimmyhlee94** [IBM/slack-wrench#36]
**Is your feature request related to a problem? Please describe.**
Sometimes when I'm building a new app from scratch, I like to set up commands, scopes, endpoints, etc on slack's website first and then create the bolt app next.

But this is time consuming and I think we should be able to generate bolt app method stubs for at least commands by inspecting the contents of the slack app page.

**Describe the solution you'd like**
Given my slack session token and a link to my app's page (https://api.slack.com/apps/<APPID>/) this tool should identify all the information required when building a bolt app to match the settings I have created on the UI:
- App Credentials
- Commands
- Select Menu
etc...

and then generate a basic bolt app prepopulated with the app credentials and some method stubs. For example, if I have a command called `/foo`, the bolt app code should have a method stub 
```js
boltApp.command('/foo', async function foo({ ack }){ /*todo*/ });
// if the command description follows established conventions, we could also generate code to parse args
```

**Describe alternatives you've considered**
I'm not aware of any existing tools that can do this. Alternative is to continue bootstrapping bots manually

**Comment by barlock** [comment]
Slack implemented this 🚀
