### ISSUE TITLE
TypeError: mockWebApi is not a function

### ISSUE THREAD

**Issue by thenationofalex** [IBM/slack-wrench#91]
**Describe the bug**

Hopefully this is okay to post, please close if not.

Followed the installation guide for @slack-wrench/jest-mock-web-client.
But when I run this test

```
import {
    MockedWebClient,
    MockWebClient,
  } from '@slack-wrench/jest-mock-web-client'
  
  import { xxxx } from '.'
  
  const SLACK_MEMBER_ID = 'U023BECGF'
  
  describe('xxxx', () => {
    let client: MockWebClient
  
    beforeEach(() => {
      MockedWebClient.mockClear()
      client = MockedWebClient.mock.instances[0]
  
      client.conversations.members.mockResolvedValue({
        ok: true,
        members: [
          SLACK_MEMBER_ID
        ]
      })
  
    it('Fetches a list', async () => {
      expect(xxxx[0]).toBe({ id: SLACK_MEMBER_ID })
    })
  })
  ```

Jest returns the following error: 

```
    TypeError: mockWebApi is not a function
      1 | const mockWebApi = require('@slack-wrench/jest-mock-web-client');
      2 | 
    > 3 | module.exports = mockWebApi(jest);
        |                  ^
      4 | 
```

I'm using 

- Typescript 3.9.7 
- Jest 26.1.0 
- @slack-wrench/jest-mock-web-client 1.2.0
- @slack/web-api 5.11.0

Thanks

**Comment by barlock** [comment]
I _think_ this has to do with how your project is handling modules. For this project, we [import the mock](https://github.com/IBM/slack-wrench/blob/master/packages/bolt-interactions/__mocks__/%40slack/web-api.ts) using typescript, you look like you're doing it in js. 

My guess is you'll need to instead do 

```js
const mockWebApi = require('@slack-wrench/jest-mock-web-client').default;
```

Does that work for you?

**Comment by thenationofalex** [comment]
@barlock 

Switching to the Typescript version of `web-api.ts`  and adjusting my `tsconfig.json` to include the `__mock__` folder fixed it right up! 

Thank you for replying so quickly!
