### ISSUE TITLE
Accepting PR for slackctl ?

### ISSUE THREAD

**Issue by Glosur** [IBM/slack-wrench#93]
Are you accepting PR for slackctl ? If so, do you happen to have some work I could base myself upon ?

**Comment by barlock** [comment]
Absolutely! 

I had started working on building it but got pulled away from it. 

https://github.com/IBM/slack-wrench/compare/events-slackctl?expand=1

☝️ This had started getting big and I wasn't a huge fan of some of the decisions I had made and never got back around to it.

One thing I had wanted to do here was switch from `yargs` to [`commander`](https://www.npmjs.com/package/commander) and then slowly roll in different top-level pieces of the app config basically corresponding to each page as each page tends to have it's own top level api.

**Comment by barlock** [comment]
Also, if you need help, you can find me on community.slack.com. I can't find how to create an account for it at the moment.

**Comment by Glosur** [comment]
I'll have a look at this

Got pretty excited seeing this package and the doc, then got a bt disappointed when I couldn't find the sources :D 
![image](https://user-images.githubusercontent.com/14371287/90261038-aed07800-de4c-11ea-9695-5cfa4b5ef8f9.png)

BTW, the jest package/slack-web-api-mock were quite hard to setup for me, but now it's a breaze to make tests ! Awesome work !

**Comment by Glosur** [comment]
Yep, don't seem to be able to join community.slack.com from my side :/

**Comment by barlock** [comment]
You can sign up here: http://slackcommunity.com/ and you'll get an invite in your email.

I'd also love help making things easier to use. Not sure if it's a documentation problem or the API is confusing. 

Please open issues as you find things that could be better.

**Comment by barlock** [comment]
Need to investigate but I think `socket mode` likely makes the intent behind slackctl erroneous. Also I think Slack got rid of my workaround for tokens 😭
